on: 
  push:
    branches:
      - test

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GCP_SERVICE_KEY: ${{ secrets.GCP_SERVICE_KEY }}
      POETRY_test: ${{ secrets.TEST_KEY }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: test

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7.12'

      - run: pip install poetry
      - run: poetry install
      - run: poetry --version
      - run: poetry run python poetry_env_test.py